name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') != 'true'
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build maven with Dependencies
        run: mvn clean compile assembly:single
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: SimpleCosmetics
          path: staging/SimpleCosmetics.jar

  prepare-release:
    runs-on: ubuntu-latest
    needs: [build]
    if: contains(github.event.head_commit.message, '[ci skip]') != 'true'
    steps:
      - uses: actions/checkout@v2

      - name: Restore release caches
        uses: actions/download-artifact@v2

      - name: Create and Publish Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Official version"
          prerelease: false
          files: |
            SimpleCosmetics/SimpleCosmetics.jar
